/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useFrame } from '@react-three/fiber'
import { useGLTF } from "@react-three/drei";

export function CityModel(props) {

  const meshRef = useRef()

  const { nodes, materials } = useGLTF("city.glb");

  useFrame(({ clock }) => {
    meshRef.current.rotation.y = clock.getElapsedTime() / 10
  })

  return (
    <group {...props} dispose={null}
    ref={meshRef}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        scale={[40, 0.06, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[0, 4.67, 0]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[-4, 4.67, -32]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[3, 4.55, 29]}
        scale={[2.85, 5, 1.28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[-5, 4.82, -16]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[33.66, 8.88, -36.02]}
        scale={[3.34, 9.31, 3.28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[-33.56, 9.32, 18.09]}
        scale={[3.34, 9.31, 3.28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[8.51, 9.49, 4.21]}
        scale={[3.34, 9.31, 3.28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        position={[22.08, 4.82, -35.76]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={nodes.Cube009.material}
        position={[33.1, 4.82, 28.46]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={nodes.Cube010.material}
        position={[-27.44, 4.82, 28.46]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={nodes.Cube011.material}
        position={[-34.85, 4.82, -16]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={nodes.Cube012.material}
        position={[-34.85, 4.82, -32.42]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={nodes.Cube013.material}
        position={[-34.85, 4.82, 0.53]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={nodes.Cube014.material}
        position={[-34.85, 4.82, 28.29]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={nodes.Cube015.material}
        position={[-15.77, 4.82, 14.97]}
        scale={[2, 5, 4.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={nodes.Cube016.material}
        position={[19.42, 4.82, 14.97]}
        scale={[2, 5, 4.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={nodes.Cube017.material}
        position={[19.42, 4.82, -24.96]}
        scale={[2, 5, 4.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={nodes.Cube018.material}
        position={[-13.14, 4.82, -24.96]}
        scale={[2, 5, 4.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={nodes.Cube019.material}
        position={[-16.25, 7.28, 0.53]}
        scale={[4.35, 7.79, 3.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={nodes.Cube020.material}
        position={[-16.25, 7.28, -12.72]}
        scale={[4.35, 7.79, 3.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={nodes.Cube021.material}
        position={[10.2, 7.28, -12.72]}
        scale={[4.35, 7.79, 3.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={nodes.Cube022.material}
        position={[23.91, 7.28, -4.01]}
        scale={[4.35, 7.79, 3.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={nodes.Cube023.material}
        position={[3, 4.55, 19.84]}
        scale={[9.87, 5, 1.28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024.geometry}
        material={nodes.Cube024.material}
        position={[-8.05, 17.22, 33.46]}
        scale={[1.83, 17.71, 1.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={nodes.Cube025.material}
        position={[19.42, 7.06, 31.92]}
        scale={[2.34, 7.7, 2.37]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026.geometry}
        material={nodes.Cube026.material}
        position={[9.88, 8.88, -29.7]}
        scale={[3.34, 9.31, 3.28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027.geometry}
        material={nodes.Cube027.material}
        position={[34.35, 7.28, -4.01]}
        scale={[4.35, 7.79, 3.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube028.geometry}
        material={nodes.Cube028.material}
        position={[34.35, 2.79, 13.18]}
        scale={[4.35, 2.94, 7.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube029.geometry}
        material={nodes.Cube029.material}
        position={[-25.68, 4.65, -32.21]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube030.geometry}
        material={nodes.Cube030.material}
        position={[-19.07, 4.05, -25.15]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031.geometry}
        material={nodes.Cube031.material}
        position={[-34.76, 4.05, -25.15]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube032.geometry}
        material={nodes.Cube032.material}
        position={[-26.94, 4.05, -25.15]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033.geometry}
        material={nodes.Cube033.material}
        position={[-26.94, 4.05, -18.02]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034.geometry}
        material={nodes.Cube034.material}
        position={[-26.94, 4.05, -8.93]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube035.geometry}
        material={nodes.Cube035.material}
        position={[-26.94, 4.05, -0.69]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube036.geometry}
        material={nodes.Cube036.material}
        position={[-26.94, 4.05, 7.36]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube037.geometry}
        material={nodes.Cube037.material}
        position={[-26.94, 4.05, 17.46]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube038.geometry}
        material={nodes.Cube038.material}
        position={[-9.92, 4.05, 17.46]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube039.geometry}
        material={nodes.Cube039.material}
        position={[-9.92, 4.05, 8.48]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube040.geometry}
        material={nodes.Cube040.material}
        position={[-0.74, 4.05, 8.48]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041.geometry}
        material={nodes.Cube041.material}
        position={[-0.74, 4.05, 14.82]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042.geometry}
        material={nodes.Cube042.material}
        position={[-0.74, 4.05, -7.96]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube043.geometry}
        material={nodes.Cube043.material}
        position={[-0.74, 4.05, -23.36]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube044.geometry}
        material={nodes.Cube044.material}
        position={[25.54, 4.05, 8.48]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube045.geometry}
        material={nodes.Cube045.material}
        position={[25.54, 4.05, 25.41]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube046.geometry}
        material={nodes.Cube046.material}
        position={[15.83, 4.05, 25.41]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube047.geometry}
        material={nodes.Cube047.material}
        position={[9.73, 4.05, 25.41]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube048.geometry}
        material={nodes.Cube048.material}
        position={[-16.25, 7.28, 25.06]}
        scale={[4.35, 7.79, 3.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube049.geometry}
        material={nodes.Cube049.material}
        position={[-16.25, 7.28, 34.95]}
        scale={[4.35, 7.79, 3.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube050.geometry}
        material={nodes.Cube050.material}
        position={[9.73, 4.05, 35.93]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube051.geometry}
        material={nodes.Cube051.material}
        position={[3, 4.55, 23.95]}
        scale={[2.85, 5, 1.28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube052.geometry}
        material={nodes.Cube052.material}
        position={[-4.94, 4.55, 23.95]}
        scale={[2.85, 5, 1.28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube053.geometry}
        material={nodes.Cube053.material}
        position={[19.42, 4.82, -13.98]}
        scale={[2, 5, 4.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube054.geometry}
        material={nodes.Cube054.material}
        position={[8, 4.05, -23.36]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube055.geometry}
        material={nodes.Cube055.material}
        position={[8, 4.05, -36.16]}
        scale={[2, 5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube056.geometry}
        material={nodes.Cube056.material}
        position={[33.66, 8.88, -36.02]}
        scale={[3.34, 9.31, 3.28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube058.geometry}
        material={nodes.Cube058.material}
        position={[26.08, 8.88, -28.09]}
        scale={[3.34, 9.31, 3.28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube057.geometry}
        material={nodes.Cube057.material}
        position={[34.35, 2.79, -18.63]}
        scale={[4.35, 2.94, 7.24]}
      />
    </group>
  );
}

useGLTF.preload("city.glb");

export default CityModel